spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dailyreport
    username: postgres
    password: postgres

#mybatis:
#  mapper-locations: classpath*:/com/example/DailyReport/mapper